using System.ComponentModel.DataAnnotations;

namespace backend.DTOs
{
    /// <summary>
    /// Payload used by the admin panel to create or update a user.
    /// <para>
    /// Two fields are deliberately absent. The QR token is generated by the
    /// server and is never client supplied. The points balance is derived from
    /// the user's transactions — to change it, record a transaction — so
    /// accepting it here would let the cached balance drift from its history.
    /// </para>
    /// </summary>
    public class UserSaveDto
    {
        [Required]
        [MaxLength(100)]
        public string UserName { get; set; } = null!;

        [Range(1, long.MaxValue)]
        public long TgUserId { get; set; }

        [MaxLength(10)]
        public string LanguageCode { get; set; } = string.Empty;

        [Range(1, int.MaxValue)]
        public int TypeUserId { get; set; }

        public bool Status { get; set; } = true;
    }
}
